### ISSUE TITLE
add reference tests based on examples in docs

### ISSUE THREAD

**Issue by hexaeder** [JuliaPlots/GraphMakie.jl#22]
as of now, one has to manually check the preview docs for a PR to see wether everything works

I think it would be good to automate this process (reference testing for all of the plots in the docs)

**Comment by hexaeder** [comment]
My current idea for this would be to transform the literate scripts in `docs/examples` to jl scripts during runtests. For that one could add save commands to the examples which are hidden away in the md export for the documentation. Running the scripts would produce some pngs which could be compared against assets using [ReferenceTests.jl](https://github.com/JuliaTesting/ReferenceTests.jl) or similar.

Additionally, there could be a new literate notebook `referencetests.jl` where we could put random code snippets to create test files. Even if those examples are not curated nor explained, i think there is value in displaying and testing different features of the package for interested users to scroll through. Stuff like https://github.com/JuliaPlots/GraphMakie.jl/issues/65#issuecomment-1055504439

**Comment by filchristou** [comment]
Currently the test environment is the same as the project environment. I think a first step would be to [separate that](https://pkgdocs.julialang.org/dev/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above).
The way I normally do this is with:
```
cd  test
julia
julia> ]
(@v1.7) pkg> activate .
(test) pkg> dev ..
(test) pkg> add CairoMakie, GLMakie, ...
```
This way the tester will not need to manually construct the needed environment  every time.

_Attention_
Doing `dev ..` in the test folder breaks the possibility of calling `(GraphMakie) pkg> test` from inside the packet. And one need to manually run `julia --project test test/runtests.jl`. The relevant issue is https://github.com/JuliaLang/Pkg.jl/issues/1585.

**Comment by filchristou** [comment]
or is there maybe a reason to go against that ?

**Comment by hexaeder** [comment]
yeah both the nested envionment and the `extras` section in project have their pros and cons...  currently i was using the latter with [TestEnv.jl](https://github.com/JuliaTesting/TestEnv.jl) to activate the test environment
