### ISSUE TITLE
Plotting a graph with given node positions

### ISSUE THREAD

**Issue by fbanning** [JuliaPlots/GraphMakie.jl#44]
As far as I understood, GraphMakie provides the `graphplot` recipe which is a neat wrapper that (among other things) plots nodes as scatterpoints and edges as linesegments. Now I do have a `SimpleDiGraph` and a `Vector{Point2{Float64}}` determining the position for each node in the graph. I can of course easily use this vector to create a `scatter`plot. I can also use the graph to create a `graphplot` showing the nodes and edges. So far, so good! :)

However, I fail to see how to connect those two and create a graph plot with predetermined node positions (i.e. without using any of the layouting algorithms). For the past hours I've tried to understand how to write a custom layout for NetworkLayout.jl because I thought that this is what I need to do but it didn't work out. Most likely, I'm just misunderstanding its interface and am approaching this in a wrong way.

Can you help me understand if what I'm trying to do is actually feasible with GraphMakie? (I sure hope so!) If yes, can you point me in the right direction of what I need to do?

**Comment by hexaeder** [comment]
Hello :)
yeah this part may be confusing. GraphMakie does not know anything about the internals of NetworkLayout. It just wants a function `layout`, any function really, which takes a `Graph` object as an input and returns a vector of node positions.
If you want to use fixed points you can just define a function which returns the same set of points for every graph:
```julia
fixed_layout = (g) -> points
```

The full example looks like this
```julia
julia> using GLMakie, GraphMakie, Graphs;

julia> positions = Point.([(0,0), (1,0), (1,1)])

julia> g = complete_graph(3);

julia> graphplot(g; layout=_->positions)
```
<img width="399" alt="grafik" src="https://user-images.githubusercontent.com/35867212/145534714-2dfbb260-c6b6-4c95-ad41-f82a0172f1f4.png">

**Comment by fbanning** [comment]
> It just wants a function layout, any function really, which takes a Graph object as an input and returns a vector of node positions.

Ah, that's the key part I was missing! Thank you for getting back to me with the explanation and a simple example. Definitely cleared things up for me and now things are working as expected. :)

It might be helpful to make this a bit clearer in GraphMakie's docs. Would you be interested in a PR for this?

**Comment by hexaeder** [comment]
Yeah for sure, PRs welcome! The docstring of `graphplot` mentions this but very briefly

https://github.com/JuliaPlots/GraphMakie.jl/blob/649f1aec493bc57fdd3ca66e57d6b5eaaf946af4/src/recipes.jl#L27

and the [part about layouts](http://juliaplots.org/GraphMakie.jl/stable/#Network-Layouts) could also be better...
