### ISSUE TITLE
Black frame around axis when moving vertices 

### ISSUE THREAD

**Issue by elkaps** [JuliaPlots/GraphMakie.jl#5]
I have no idea where it's coming from but when moving a vertex this black frame shows up:

![black-border](https://user-images.githubusercontent.com/44770441/114275796-267a9500-9a24-11eb-9af5-f87b95d54086.png)

**Comment by SimonDanisch** [comment]
Oh interesting :D Looks like the axis splines!

**Comment by hexaeder** [comment]
I'll close this issue since i can not reproduce and the code is enterly different now anyway. Feel free to reopen though.
