### ISSUE TITLE
reset camera view

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaPlots/GraphMakie.jl#81]
Hi,
I'm using this package in Pluto notebook and it works very well with the WGLMakie backend. It is very easy though to accidentally select some rectangular area, zoom in, and then you have a hard time recentering the view. Maybe some button could be displayed to reset the camera?

**Comment by hexaeder** [comment]
there is an interaction for resetting the axis limits registered by default, it is bound to `ctrl + leftclick` (see [Makie docs](https://makie.juliaplots.org/dev/examples/blocks/axis/#limit_reset)). If you don't want to use the [rectangle selection zoom](https://makie.juliaplots.org/dev/examples/blocks/axis/#rectangle_selection_zoom) interaction in the first place, you may disable it by
```
fig, ax, p = graphplot(...)
deregister_interaction!(ax, :rectanglezoom)
```

**Comment by CarloLucibello** [comment]
> there is an interaction for resetting the axis limits registered by default, it is bound to ctrl + left-click 

thanks, I have not much experience with Makie and was not aware of that.
